<template>
  <v-container fluid>
    <v-row>
      <v-col>
        <span class="title">Exercise 4.4.1 e) *</span>
        <br>
        A group with a finite number of subgroups is finite.
      </v-col>
    </v-row>
    <v-row class="mr-2">
      <v-col cols="12">
        <span class="title mr-2">Proof</span>
        <br>
        Each element is in a subgroup generated by itself. As a set, the whole group is a sum 
        of these cyclic subgroups. Can one of them be infinite?
      </v-col>
    </v-row>
    <v-row class="mr-2">
      <v-col cols="12">
        If a cyclic group \( \langle a \rangle \) is infinite then it has infinite number of subgroups
        $$
          \langle a \rangle \supset \langle a^2 \rangle \supset \langle a^4 \rangle \supset \ldots 
        $$
      </v-col>
    </v-row>
    <v-row class="mr-2">
      <v-col cols="12">
        So none of our cyclic subgroups can be infinite. As a set-theoretical sum
        of finite sets, the whole group is finite.
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
import { runDelayed } from '@/lib/delayed'

export default {
  mounted() {
    console.log('Component Exe01e mounted');
    runDelayed();
  }
    
}
</script>