<template>
  <v-container fluid>
    <v-row>
      <v-col>
        <span class="title">Exercise 4.4.39</span>
        <br>
        Prove that if \( G \) is a cyclic group of order \( m \) and \( d | m \),
        then G must have a subgroup of order \( d \).
      </v-col>
    </v-row>
    <v-row class="mr-2">
      <v-col cols="12">
        <span class="title mr-2">Solution</span>
        <br>
        Look at \( \mathbb{Z}_{12} \): \( 4 | 12 \) and \( \langle 3 \rangle \) has order \( 4 \).
        <br>
        The subgroup looked out for is generated by \( a^{m/d} \): \( (a^{m/d})^d = a^m = 1 \) and for \( i \lt d \),
        \( i \cdot m/d \lt m \) and \( (a^{m/d})^i = a^{im/d} \ne 1 \).
        \( \Box \)
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
import { runDelayed } from '@/lib/delayed'

export default {
  mounted() {
    console.log('Component Exe32 mounted');
    runDelayed();
  }
    
}
</script>

<style scoped>
.theorem {
  font-style: italic;
}

#fact {
  border-style: solid;
  border-width: 1px;
  border-color: darkgray;
  border-radius: 4px;
  padding: 8px;
  margin-right: 8px;
  word-spacing: 2px;
}

.paragraph {
  text-justify: distribute;
}

</style>