<template>
  <v-container fluid>
    <v-row>
      <v-col>
        <span class="title">Exercise 4.4.32</span>
        <br>
        Let \( G \) be finite cyclic group of order \( n \) generated by \( x \). 
        Show that if \( y = x^k \) where \( \text{gcd} (k, n) = 1 \),
        then \( y \) must be a generator of \( G \).
      </v-col>
    </v-row>
    <v-row class="mr-2">
      <v-col cols="12">
        <span class="title mr-2">Solution</span>
        <br>
        Order of \( y \) is \( n / \text{gcd}(k, n) = n\) (we use Theorem 4.13). 
        So \( y \) generates the group.
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
import { runDelayed } from '@/lib/delayed'

export default {
  mounted() {
    console.log('Component Exe32 mounted');
    runDelayed();
  }
    
}
</script>

<style scoped>
.theorem {
  font-style: italic;
}

#fact {
  border-style: solid;
  border-width: 1px;
  border-color: darkgray;
  border-radius: 4px;
  padding: 8px;
  margin-right: 8px;
  word-spacing: 2px;
}

.paragraph {
  text-justify: distribute;
}

</style>